# Generated by Django 2.2 on 2021-07-03 06:19

from django.db import migrations, models
import us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('pending', models.BooleanField(default=True)),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateTimeField(auto_now_add=True)),
                ('tracking_number', models.CharField(default=us.models.generate_activationcode, editable=False, max_length=255)),
                ('delivery_date', models.DateTimeField()),
                ('destination', models.CharField(max_length=255)),
                ('take_off_point', models.CharField(max_length=255)),
                ('sender_detail', models.CharField(max_length=255)),
                ('receiver_detail', models.CharField(max_length=255)),
                ('shipment_type', models.CharField(default='Travel Box', max_length=255)),
                ('weight', models.CharField(default='20.kg', max_length=255)),
                ('content', models.CharField(default='Family Treasure', max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('sender_name', models.CharField(max_length=255)),
                ('receiver_name', models.CharField(max_length=255)),
                ('sender_country_flag', models.ImageField(blank=True, max_length=255, null=True, upload_to='picture')),
                ('receiver_country_flag', models.ImageField(blank=True, max_length=255, null=True, upload_to='picture')),
                ('service_type', models.CharField(default=' Express Delivery', max_length=255)),
                ('status', models.CharField(default='Dispatched', max_length=255)),
                ('pending', models.BooleanField(default=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
